### ISSUE TITLE
How to tag issues?

### ISSUE THREAD

**Issue by adanieljohnson** [WFU-TLC/flc_discussion_board#13]
When I start a new issue here, how do I tag it with one of the existing tags (tip, etc.)? Seems simple, but cannot find it.

**Comment by medewitt** [comment]
I think only the owners can tag things, right @francojc ?

**Comment by francojc** [comment]
It's under Labels on the right-hand menu once you select a discussion thread. I'm not sure if there are restrictions on the permissions. 

If you don't see the following on your screen, then it may in fact be limited to repository owners.

<img width="507" alt="screen shot 2019-02-01 at 3 08 15 pm" src="https://user-images.githubusercontent.com/1140826/52147016-6e772380-2633-11e9-9967-53b3f3338883.png">

**Comment by adanieljohnson** [comment]
Jerid's right, you have to be the owner to add labels. Mere mortals are not allowed.
D
