### ISSUE TITLE
Problem with new package - finalfit

### ISSUE THREAD

**Issue by adanieljohnson** [WFU-TLC/flc_discussion_board#17]
Read about the `finalfit` package for creating summary data tables, and wanted to try it out. Downloaded, installed, but when I called, this is what I got:
```
> library(finalfit)
Error: package or namespace load failed for ‘finalfit’:
 object ‘new_pillar_type’ is not exported by 'namespace:pillar'
```
Tried to Google the error, but no luck. Tried reinstalling direct from developer, and updating pillar, but still stalls at this step. Developer documentation is no help. Ideas?

**Comment by francojc** [comment]
Not sure. I haven't worked with this package. Check, however, that the install completed and did not have an exit 0 status --which can happen with packages that need to be compiled from source. 

Not an answer to your question, but a suggestion for another package to take a look at for table summaries, specifically for model output is the [`stargazer`](https://cran.r-project.org/web/packages/stargazer/index.html) package. The vignette is found [here](https://cran.r-project.org/web/packages/stargazer/vignettes/stargazer.pdf).
