### ISSUE TITLE
How to modify commands provided by a package

### ISSUE THREAD

**Issue by adanieljohnson** [WFU-TLC/flc_discussion_board#20]
Had something come up when coding I am not sure how to respond to. I've gotten warnings saying a particular command I typed is "soft-deprecated" and I should use a different one. That is easy to fix. What if the command is one provided by a package (I can see it in trace-back), and not one I typed. Is updating the package version the solution, or do I need to do more?

Sorry I do not have a specific example; I copied it then lost the file.

**Comment by medewitt** [comment]
Hi Dan, I don't have a great solution at this time. The good news is that the function within the package that you use is soft-deprecated meaning that it hasn't gone away yet. I would check on cran to make sure that the package you are still using is supported and not orphaned. Eventually, the package maintainer should fix their package based on the dependencies.

CRAN generally doesn't let updates to existing packages if breaking changes are not repaired in packages that depend on them.
