### ISSUE TITLE
ggplot visualizations not showing up

### ISSUE THREAD

**Issue by ejmasicampo** [WFU-TLC/flc_discussion_board#5]
Hi all,
I played around with rio and ggplot and documented my work. I published what I did to my website but the visualizations are showing up as broken images. The data seem to be importing fine, and everything else looks good. But the visualizations aren't there. The visualizations do show up locally when I view the html files on my computer. But when I view them on the website, the images don't show up. Can anyone tell me why? Thanks for the help!
E.J.

**Comment by medewitt** [comment]
@ejmasicampo it looks like you didn't push all the .png files to your github. When I look at the html code it is looking for something called "pre_work_files/figure-html/unnamed-chunk-8-1.png" and there isn't anything in that directory in your github, hence the broken paths.

I would ensure that you push everything into your github directory and it should render correctly. 
In the terminal you could do:
```
git add --a
git commit -m "add everything"
git push
```
And that should commit everything to the online repo

**Comment by ejmasicampo** [comment]
Ah, yes. Solved. Thank you! I was only pushing the pre_work.html file and my data set thinking those were the only files that were changing or being added. I didn't realize that those images were also being created.
