### ISSUE TITLE
Textual analysis

### ISSUE THREAD

**Issue by brown-allen** [WFU-TLC/flc_discussion_board#8]
@johnstc - I recall you mentioning that you started work with the gutenbergr package. Any new discoveries with it? Remaining questions? Types of tasks you think it might be useful for?

**Comment by francojc** [comment]
Here's a good tutorial for `gutenbergr` from  the creators at [rOpenSci](https://ropensci.org/): https://ropensci.org/tutorials/gutenbergr_tutorial/
